name: Push to PPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install devscripts debhelper-compat dput cli-common-dev libunwind8-dev libcurl4-openssl-dev
        
      - name: Initialize offline package
        run: |
          chmod +x initializeoffline.sh
          ./initializeoffline.sh
        
      - name: Make original package
        run: |
          tar cfv ../msbuild_16.9.11.orig.tar .
          xz -9 ../msbuild_16.9.11.orig.tar

      - name: Build source package
        run: debuild -S -sa
        
      - name: Push to Launchpad
        run: dput ppa:eofla/msbuild ../msbuild_16.9.11_source.changes
