name: Push to PPA (amend with original source) (Debug level 2 for validation)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install devscripts debhelper-compat dput curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev
        
      - name: Download original source
        run: wget --output-document=../msbuild_16.10.1.orig.tar.xz https://launchpad.net/~eofla/+archive/ubuntu/msbuild/+sourcefiles/msbuild/1:16.10.1-0ppa1/msbuild_16.10.1.orig.tar.xz

      - name: Build source package
        run: debuild -S
          
      - name: Setup tmate session for validation
        uses: mxschmitt/action-tmate@v3
        
      - name: Push to Launchpad
        run: dput ppa:eofla/msbuild ../msbuild_16.10.1-0ppa2_source.changes
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
